version: "3.8"
services:
  db_user:
    image: postgres:9.6.21-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user
    ports:
      - "5000:5432"
    networks:
      - backend
    container_name: db-user

networks:
  backend:
